package util;

public enum TypeOfAnswer {
    OBJECTNOTEXIST,
    DUPLICATESDETECTED,
    ISNTMAX,
    PERMISSIONDENIED,
    SUCCESSFUL,
    SQLPROBLEM,
    EMPTYCOLLECTION,
    ALREADYREGISTERED,
    NOTMATCH
}
